[package]
name = "e-charlar"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
rand = "0.9.0"
futures = "0.3.31"
anyhow = "1.0.97"
